version: "2"

run:
  timeout: 5m

linters:
  default: standard
  enable:
    - errorlint
    - exhaustive
    - misspell
    - nilerr
    - revive
  settings:
    exhaustive:
      default-signifies-exhaustive: true
    revive:
      rules:
        - name: exported
          disabled: false

formatters:
  enable:
    - gofmt
    - goimports
